// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lqY3zig7wJUEdXsEq49ttpzrZgZ8Cjk',
    appId: '1:766766569628:web:baf8f394a59dad4eed7559',
    messagingSenderId: '766766569628',
    projectId: 'e-pengaduan-64f1d',
    authDomain: 'e-pengaduan-64f1d.firebaseapp.com',
    storageBucket: 'e-pengaduan-64f1d.appspot.com',
    measurementId: 'G-R0716ZWRWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBmrkt0iY3r_bQSs5OzX-pnCbJrJqriiA',
    appId: '1:766766569628:android:1e2b0aced4da37e7ed7559',
    messagingSenderId: '766766569628',
    projectId: 'e-pengaduan-64f1d',
    storageBucket: 'e-pengaduan-64f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenlWwf4JS82lWwS2uWp9Ogx4FVajPX6E',
    appId: '1:766766569628:ios:356bd5189da2d03aed7559',
    messagingSenderId: '766766569628',
    projectId: 'e-pengaduan-64f1d',
    storageBucket: 'e-pengaduan-64f1d.appspot.com',
    iosClientId: '766766569628-474pk38mbamr48lbq1ue1lel2hp9died.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPengaduanMasyarakatBna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDenlWwf4JS82lWwS2uWp9Ogx4FVajPX6E',
    appId: '1:766766569628:ios:356bd5189da2d03aed7559',
    messagingSenderId: '766766569628',
    projectId: 'e-pengaduan-64f1d',
    storageBucket: 'e-pengaduan-64f1d.appspot.com',
    iosClientId: '766766569628-474pk38mbamr48lbq1ue1lel2hp9died.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPengaduanMasyarakatBna',
  );
}
